#
# **This is an example configuration file. Uncomment the lines that need to be enabled.**
#
#
ServiceKey: your_service_key:your_service_name  # - env var: SWO_SERVICE_KEY
# Sampling:
#   TracingMode: enabled  # - env var: SWO_TRACING_MODE
# PrependDomain: true  # - env var: SWO_PREPEND_DOMAIN
# HostAlias: my-alias  # - env var: SWO_HOSTNAME_ALIAS
# SQLSanitize: 2  # - env var: SWO_SQL_SANITIZE
# TransactionSettings:
# - Type: url
#   RegEx: \s+\d+\s+
#   Tracing: disabled
# - Type: url
#   Extensions:
#   - .jpg
#   Tracing: disabled
# Disabled: false  # - env var: SWO_DISABLED
# Ec2MetadataTimeout: 1000 # - env var: SWO_EC2_METADATA_TIMEOUT
# DebugLevel: warn  # - env var: SWO_DEBUG_LEVEL
# TriggerTrace: true # - env var: SWO_TRIGGER_TRACE
# Proxy: https://proxy_user:pwd@proxy_host:3307 # - env var: SWO_PROXY
# ProxyCertPath: /proxy.crt # - env var: SWO_PROXY_CERT_PATH
