name: test

on:
  pull_request: null
  push:
    branches:
      - master

jobs:
  license-check:
    runs-on: ubuntu-latest
    name: License header check
    steps:
      - run: ./license_check.sh
  fmt-check:
    runs-on: ubuntu-latest
    name: "`gofmt` check"
    steps:
      - uses: Jerome1337/gofmt-action@v1.0.5
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goversion: ['1.19', '1.20']
    name: Go ${{ matrix.goversion }} tests
    env:
      SW_APM_DEBUG_LEVEL: 1
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.goversion }}
      - name: Install dependencies
        run: |
          go get golang.org/x/tools/cmd/cover
          go get github.com/mattn/goveralls
          go install github.com/wadey/gocovmerge@latest
          go get -t -v ./...
      - name: Go vet
        run: go vet ./...
      - name: Run tests
        working-directory: ./v1
        run: |
          pushd solarwinds_apm/internal/reporter
          ./certgen.sh
          popd

          pushd solarwinds_apm
          go build -v github.com/solarwindscloud/solarwinds-apm-go/v1/solarwinds_apm github.com/solarwindscloud/solarwinds-apm-go/v1/solarwinds_apm/internal/reporter github.com/solarwindscloud/solarwinds-apm-go/v1/solarwinds_apm/internal/log github.com/solarwindscloud/solarwinds-apm-go/v1/solarwinds_apm/internal/bson github.com/solarwindscloud/solarwinds-apm-go/v1/solarwinds_apm/internal/metrics github.com/solarwindscloud/solarwinds-apm-go/v1/solarwinds_apm/internal/config github.com/solarwindscloud/solarwinds-apm-go/v1/solarwinds_apm/internal/host
          go test -v -race -covermode=atomic -coverprofile=cov.out -coverpkg github.com/solarwindscloud/solarwinds-apm-go/v1/solarwinds_apm/internal/reporter,github.com/solarwindscloud/solarwinds-apm-go/v1/solarwinds_apm/internal/log,github.com/solarwindscloud/solarwinds-apm-go/v1/solarwinds_apm/internal/bson,github.com/solarwindscloud/solarwinds-apm-go/v1/solarwinds_apm/internal/metrics,github.com/solarwindscloud/solarwinds-apm-go/v1/solarwinds_apm,github.com/solarwindscloud/solarwinds-apm-go/v1/solarwinds_apm/internal/config,github.com/solarwindscloud/solarwinds-apm-go/v1/solarwinds_apm/internal/host
          pushd internal/reporter/
          go test -v -race -covermode=atomic -coverprofile=cov.out
          popd
          pushd internal/metrics/
          go test -v -race -covermode=atomic -coverprofile=cov.out
          popd
          pushd internal/log/
          go test -v -race -covermode=atomic -coverprofile=cov.out
          popd
          pushd internal/config/
          go test -v -race -covermode=atomic -coverprofile=cov.out
          popd
          pushd internal/host/
          go test -v -race -covermode=atomic -coverprofile=cov.out
          popd
          popd
          gocovmerge solarwinds_apm/cov.out solarwinds_apm/internal/reporter/cov.out solarwinds_apm/internal/metrics/cov.out solarwinds_apm/internal/log/cov.out solarwinds_apm/internal/config/cov.out solarwinds_apm/internal/host/cov.out > coverage.txt
          pushd solarwinds_apm/internal/reporter
          rm for_test.crt for_test.key
          popd

      - uses: codecov/codecov-action@v1
        if: matrix.goversion == '1.20'

      - uses: dominikh/staticcheck-action@v1.2.0
        if: matrix.goversion == '1.20'
        with:
          install-go: false
          cache-key: ${{ matrix.goversion }}
